### ISSUE TITLE
Wrong postgresql version

### ISSUE THREAD

**Issue by beuwolf-u** [peter-evans/nominatim-k8s#23]
hey, on the kubernetes deploy, the canary starts fine but wen trys to do the copy it fail, reading a little bit about the error it show 

tar: Removing leading `/' from member names
tar: /var/lib/postgresql/9.3/main: Cannot stat: No such file or directory

but it use the 9.5 so looking a bit the code on the docker-entrypoint.sh it need a fix on the line 12 to point to the right version

**Comment by peter-evans** [comment]
Hi @beuwolf-u 

Thanks for letting me know. Released a fix.
