### ISSUE TITLE
PostgreSQL Threads

### ISSUE THREAD

**Issue by auro** [peter-evans/nominatim-k8s#26]
Hi peter!

I would like to push a feature to your code - the ability to specify postgresql threads as an env var.

I thing it can be useful.

Could you give me permission to create a branch so you can evaluate the changes?

Thank you.

Auro

**Comment by auro** [comment]
`NOMINATIM_PG_THREADS=${NOMINATIM_PG_THREADS:=2}`

`    sudo -u nominatim /srv/nominatim/build/utils/setup.php --osm-file $NOMINATIM_DATA_PATH/$NOMINATIM_DATA_LABEL.osm.pbf --all --threads $NOMINATIM_PG_THREADS
`

**Comment by peter-evans** [comment]
Hi @auro 

If you would like to contribute to the project yourself then you can do the following:
1. Fork the repository
2. In your fork, create a new branch with the changes you want to make
3. Create a pull request from your fork to this repository

See this guide for more detail:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Or if you prefer, I can look into adding the changes you want to make for you.

**Comment by auro** [comment]
Hi @peter-evans how are you? Just made a push request, thank you for your help.
