### ISSUE TITLE
K8s Stateful Sets and volumes?

### ISSUE THREAD

**Issue by tombh** [peter-evans/nominatim-k8s#31]
Am I missing something, it seems to me that k8s Stateful Sets and their guarantees for consistent volume association would be an obvious use case here. You could even use k8s' volume cloning feature for scaling https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource

**Comment by peter-evans** [comment]
Hi @tombh 

I'm quite sure you aren't missing anything. I started this project almost 5 years ago and I seem to remember that k8s Stateful Sets did not exist at that point (or maybe they were in alpha, I forget). I don't use this project now and just keep it alive with updates for those who do. At the time it worked very well for my needs but I'm sure there are better/alternative ways to design this now. Of course any design being "better" will then come with its own set of trade-offs. 😄

**Comment by tombh** [comment]
Ooh, that totally makes sense then! Yeah back then there weren't so many options. So if it works it works :)
