### ISSUE TITLE
No gzip file created by nominatim-k8s canary deployment

### ISSUE THREAD

**Issue by Junaid-Ahmed94** [peter-evans/nominatim-k8s#39]
I have been trying to run the nominatim-k8s deployment but the stable deployment keeps failing the health check. After modifying the deployment yaml i found the following in the logs for pod

```
Activated service account credentials for: [nominatim-storage-sa@MY-GCP-PROJECT.iam.gserviceaccount.com]
Updated property [core/project].
CommandException: No URLs matched: gs://MY-GCP-PROJECT-nominatim/maldives-20161213/*.tgz*
CommandException: 1 file/object could not be transferred.
cat: '/srv/nominatim/data/maldives-20161213.tgz_*': No such file or directory
```

After this i checked the canary deployment and that seems to work fine without any issues.

```
2020-10-22 10:38:38 == Setup finished.
 * Stopping PostgreSQL 9.5 database server
   ...done.
tar: Removing leading `/' from member names
Activated service account credentials for: [nominatim-storage-sa@MY-GCP-PROJECT.iam.gserviceaccount.com]
Updated property [core/project].
Copying file:///srv/nominatim/data/maldives-20161213.tgz_aa [Content-Type=application/octet-stream]...
- [1/1 files][136.2 MiB/136.2 MiB] 100% Done
Operation completed over 1 objects/136.2 MiB.
 * Starting PostgreSQL 9.5 database server
   ...done.
==> /var/log/apache2/access.log <==
2020-10-22 10:38:38 == Setup finished.
 * Stopping PostgreSQL 9.5 database server
   ...done.
tar: Removing leading `/' from member names
Activated service account credentials for: [nominatim-storage-sa@MY-GCP-PROJECT.iam.gserviceaccount.com]
Updated property [core/project].
Copying file:///srv/nominatim/data/maldives-20161213.tgz_aa [Content-Type=application/octet-stream]...
- [1/1 files][136.2 MiB/136.2 MiB] 100% Done
Operation completed over 1 objects/136.2 MiB.
 * Starting PostgreSQL 9.5 database server
   ...done.
==> /var/log/apache2/access.log <==
```
I checked the cloud storage and a file was present there but without and file extension `gs://MY-GCP-PROJECT-nominatim/maldives-20161213`. Its is missing the file extension *.tgz_* that is expected by stable deployment.

**Comment by peter-evans** [comment]
Hi @Junaid-Ahmed94 

`gs://MY-GCP-PROJECT-nominatim/maldives-20161213` is the bucket name, not the file. There should be archive files inside that bucket.

Not sure what the issue could be. Check the permissions are setup correctly for the stable pods.

**Comment by Junaid-Ahmed94** [comment]
Hi @peter-evans 

The Permissions were set properly on the bucket. I went through the docker-entrypoint.sh file and after slightly altering the [line#50](https://github.com/peter-evans/nominatim-k8s/blob/master/docker-entrypoint.sh#L50), the zip file was created without issues. I have done this step manually for now, will have to modify the docker-entrypoint.sh file and recreate the docker image for it to work every time.

[line#50](https://github.com/peter-evans/nominatim-k8s/blob/master/docker-entrypoint.sh#L50) and [line#68](https://github.com/peter-evans/nominatim-k8s/blob/master/docker-entrypoint.sh#L68) together are causing issue. [line#50](https://github.com/peter-evans/nominatim-k8s/blob/master/docker-entrypoint.sh#L50) removes the tgz extension while copying the file but [line#68](https://github.com/peter-evans/nominatim-k8s/blob/master/docker-entrypoint.sh#L68) expects the file in bucket to have tgz extension.

**Comment by peter-evans** [comment]
I'm no longer using this project, but I don't think this code has changed and it was working fine in the past. 

I wonder if the issue is because when testing with the maldives data the total database size is less than 1GB, so the split only creates one file instead of multiple parts. That could be why the extension is missing. You might find that when the database is larger than 1GB the split will occur and your fix no longer works. Let me know if that happens.
https://github.com/peter-evans/nominatim-k8s/blob/master/docker-entrypoint.sh#L42
